<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text18_text18</name>
   <tag></tag>
   <elementGuidId>8db7e89a-de1e-4aaa-a751-e77443fe4d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1da7d4e2-5f5c-48bb-bf9d-4e66fb2e5d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e4380a1-79af-48df-872f-f1c511d0db44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text18</value>
      <webElementGuid>5d62b5a1-1df0-4c47-b9af-3d45c8d3a894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text18&quot;)</value>
      <webElementGuid>bd26b551-0fcf-45fd-b116-a9eb30fd160c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text18']</value>
      <webElementGuid>3e971c50-1e4c-4bd7-9188-52d566d9f54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[18]</value>
      <webElementGuid>455ed8a9-1d7f-44df-827e-5f08f97bc23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text18']</value>
      <webElementGuid>c954a60b-7102-43ad-bb0c-7ae9d17a719a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
