<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text8_text8</name>
   <tag></tag>
   <elementGuidId>1e22a70e-8a6c-4001-89b7-6d9858f7ac06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abecefd3-3f70-4b13-9151-e66ad987372d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7b620fd-4920-4907-a043-9dfa93c6693a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text8</value>
      <webElementGuid>3cd162c5-f4ca-44b6-bf98-3fda46cba387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text8&quot;)</value>
      <webElementGuid>fa3b4bc0-2a3d-44d2-b529-48ca02b0c320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text8']</value>
      <webElementGuid>bdd9e2e4-e20b-4fe0-ad4c-a26726f93d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>1740601a-81f7-4fa5-88d2-c107706f3e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text8']</value>
      <webElementGuid>a8c5d1c8-2a10-41a6-b317-d6c300fed491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
