<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio6_radio7</name>
   <tag></tag>
   <elementGuidId>f95981d6-e1d5-498e-b466-4097d1dd2af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fefbb4e9-bced-484a-8327-5937c4f05d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3808762c-f2ab-46fd-8094-0abca2a0687b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio7</value>
      <webElementGuid>27ca8d39-8304-4f71-857a-5b7b36b36ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio7</value>
      <webElementGuid>e578586b-0b60-4d1a-930c-f59270cdb0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio7&quot;)</value>
      <webElementGuid>8c2d68b3-e621-49ec-92d0-ef22e6c8fb70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio7']</value>
      <webElementGuid>8048dc0c-fe5c-4f09-9fa3-a3777d70d548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[27]</value>
      <webElementGuid>93ceae99-be59-41e9-ae3e-9c50dd9bc4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio7']</value>
      <webElementGuid>75c61747-8b60-436a-b730-8ef1f22bc15c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
