<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox9_checkbox10</name>
   <tag></tag>
   <elementGuidId>0972cdf0-62af-4f4a-b2a0-7d0538ddaa24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3b6ed1f-fd02-4c75-aa09-65579d3c0502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6ccc34b0-7770-4e0e-aea1-eecb6e24ff6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox10</value>
      <webElementGuid>9b50ff9a-80f4-4dde-9856-e8140c6afdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox10</value>
      <webElementGuid>2ddabfec-9107-4685-b8e4-845ddb80fc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox10&quot;)</value>
      <webElementGuid>12472927-3fe6-411a-884a-13bcb6e63623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox10']</value>
      <webElementGuid>8b4846f8-4f6b-4be1-b740-b623020f292a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[20]</value>
      <webElementGuid>ad3877f8-a2ed-4f3a-ad47-f6bf089daad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox10']</value>
      <webElementGuid>fce009f2-9f99-4d79-8e3e-8553213c383e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
